spring.datasource.url=jdbc:mysql://jenifa-db.cjqsqwumim0r.ap-south-1.rds.amazonaws.com:3306/jenifa_db
spring.datasource.username=jenifa
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
